In [3]:
import numpy as np

n = 4

m = np.random.randint(0,11,(n,n)) # Changed to create an n x n 2D array
print(m,'\n')

for i in range(n):
    for j in range(n):

        v = 0

        if i+1 < n:
            v += m[i+1,j]

        if i-1 >= 0:
            v += m[i-1,j]

        if j+1 < n:
            v += m[i,j+1]

        if j-1 >= 0:
            v += m[i,j-1]

        print(v,end=" ")
    print()

[[ 2  2  9  1]
 [ 5  8  6  1]
 [10  7  1  7]
 [ 6  1  8  5]] 

7 19 9 10 
20 20 19 14 
18 20 28 7 
11 21 7 15 


In [7]:
n = 4

m = np.random.randint(0,11,(n,n)) # Changed to create an n x n 2D array
print(m,'\n')

for i in range(n):
    for j in range(n):

        v = 1

        if i+1 < n and m[i+1,j] > m[i,j]:
            v = 0

        if i-1 >= 0 and m[i-1,j] > m[i,j]:
            v = 0

        if j+1 < n and m[i,j+1] > m[i,j]:
            v =0

        if j-1 >= 0 and m[i,j-1] > m[i,j]:
            v =0

        print(v,end=" ")
    print()

[[ 2  5  3  3]
 [ 7 10 10  9]
 [ 6  6  7  9]
 [ 3  8  0  1]] 

0 0 0 0 
0 1 1 0 
0 0 0 1 
0 1 0 0 


In [13]:
n= 4
m = np.random.randint(0,11,(n,n)) # 0 e 11 numeros para selecionar (n,n) tamanho
print(m, '\n')
for i in range(n):#  linha
  for j in range(n): # coluna
    v = 1 # valor guardado
    if i+1 < n and m[i+1,j] > m[i,j]: # i+1 < n varificar o limite da matriz// m[i+1,j] > m[i,j]: comparar se é maior ou menor
            v = 0
    if i-1 >= 0 and m[i-1,j] > m[i,j]:
            v = 0
    if j+1 < n and m[i,j+1] > m[i,j]:
            v =0
    if j-1 >= 0 and m[i,j-1] > m[i,j]:
            v =0

    print(v,end=" ")
  print()

[[ 3  6 10  1]
 [ 9 10  9  1]
 [ 4 10  2  8]
 [ 3  1  0  4]] 

0 0 1 0 
0 1 0 0 
0 1 0 1 
0 0 0 0 


In [40]:
t = 20
m = np.random.randint(0,100,(t))
print(m)

maior = m.max()
menor = m.min()
media = m.mean()


zero = (m < media)
zero1 = (m  == media)
zero2 = (m  > media)
maximo = (m  == maior)
minimo = (m  == menor)

m[zero] = -1
m[zero1] = 0
m[zero2] = 1

m[maximo] = 9

m[minimo] = -9

print(m)

[83 20 75 39 72 88  6 12 31 28  9 93 58 49 62  5 74 89 68  8]
[ 1 -1  1 -1  1  1 -1 -1 -1 -1 -1  9  1  1  1 -9  1  1  1 -1]
